# Generated by Django 4.2.30 on 2026-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性'), (3, 'その他')], default=1, verbose_name='性別'),
        ),
    ]
